id = "morganwm-github-fork-theme"
name = "MorganWM Github Fork Theme"
version = "0.0.1"
schema_version = 1
authors = ["morganwm"]
description = "A Dimmer Version of Github Dark"
repository = "https://github.com/morganwm/zed-theme"
